// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgs7h_jv3rSxnmH3fpAbOUDsnhLBkQMq4',
    appId: '1:529573775474:web:66aebd78d195b427261aeb',
    messagingSenderId: '529573775474',
    projectId: 'skill-search-model',
    authDomain: 'skill-search-model.firebaseapp.com',
    storageBucket: 'skill-search-model.appspot.com',
    measurementId: 'G-3PXSMME40W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUabXyWSZjdTs54PmQVJ6PcMZ-B86Wq6g',
    appId: '1:529573775474:android:e38fcfeb57b5e8e1261aeb',
    messagingSenderId: '529573775474',
    projectId: 'skill-search-model',
    storageBucket: 'skill-search-model.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAVPknM9O3H_-NzaAOHxkEyKLSfMtpbqA',
    appId: '1:529573775474:ios:595b52a5b3a36621261aeb',
    messagingSenderId: '529573775474',
    projectId: 'skill-search-model',
    storageBucket: 'skill-search-model.appspot.com',
    iosBundleId: 'com.example.skillSearchModel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAVPknM9O3H_-NzaAOHxkEyKLSfMtpbqA',
    appId: '1:529573775474:ios:595b52a5b3a36621261aeb',
    messagingSenderId: '529573775474',
    projectId: 'skill-search-model',
    storageBucket: 'skill-search-model.appspot.com',
    iosBundleId: 'com.example.skillSearchModel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgs7h_jv3rSxnmH3fpAbOUDsnhLBkQMq4',
    appId: '1:529573775474:web:74fa7fbee0b7969b261aeb',
    messagingSenderId: '529573775474',
    projectId: 'skill-search-model',
    authDomain: 'skill-search-model.firebaseapp.com',
    storageBucket: 'skill-search-model.appspot.com',
    measurementId: 'G-56ZMDDSK8Z',
  );
}
